spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3308/article2?characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
      username: root
      password: 123456
#配置日志
mybatis-plus:
  mapper-package: com.**.mapper
  # 对应的 XML 文件位置
  mapper-locations: classpath*:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.example.entity
server:
  port: 9999



